### ISSUE TITLE
Install plugin on windows

### ISSUE THREAD

**Issue by ryleymcc** [PlotJuggler/plotjuggler-CAN-dbs#7] opened 2021-09-26 19:18 UTC
I have been trying for hours to install this plugin alongside my windows PlotJuggler installation. I get an error when I build using CMake "MinGW makefile" ..
PlotJuggler_LIBRARY and PlotJuggler_LIBRARY_DIR can't be found.

Would love to use plotjuggler to reverse engineer some Canbus signals and this plugin should come standard with plotjuggler.

**Comment by ozzdemir** [comment] 2021-09-27 07:28
For CMake to found the PJ Libraries, I install PJ systemwide (in linux, with sudo make install). You can try its' Windows counterpart.

**Comment by ryleymcc** [comment] 2021-09-28 07:23
> For CMake to found the PJ Libraries, I install PJ systemwide (in linux, with sudo make install). You can try its' Windows counterpart.

I am not great with this stuff and I seem to always get errors. I have used the PJ windows installer and plot juggler runs but now I'm not sure how to add plugins. Can you link me to a guide to get this plugin (or plugins in general) installed on windows.

**Comment by Inquisitive-ME** [comment] 2022-01-15 05:16
I know this is rather old, but I can't get this plugin to build in Linux either. It seems like the way to build plugins is broken. I installed Plot Juggler as described and when I try to build this project it can't find it

I am running:

mkdir build; cd build
cmake -D Qt5_DIR=~/Qt/5.15.8/gcc_64/lib/cmake/Qt5/ ..

And I get

CMake Error at /usr/local/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PlotJuggler (missing: PlotJuggler_LIBRARY)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPlotJuggler.cmake:54 (find_package_handle_standard_args)
  CMakeLists.txt:36 (find_package)

This is on Ubuntu 21.10

**Comment by ozzdemir** [comment] 2022-01-15 17:49
Hi @Inquisitive-ME, Can you verify the following directory/files exist? If you were able to install Plotjuggler systemwide, those should exist.
```
/usr/local/include/PlotJuggler
/usr/local/lib/libplotjuggler_plugin_base.a
```
I verified your problem by removing Plotjuggler installation from those directories and got the same error you got. After I installed PJ again (not as catkin package, but as a regular cmake project using following schema). I again was able to build this plugin. I hope that you also succeed
```
cd Plotjuggler
mkdir build; cd build;
cmake ..
make -j12
sudo make install
```

**Comment by Inquisitive-ME** [comment] 2022-01-15 19:27
Yes I have both that directory and the library. I don't understand how this could work PlotJuggler does not install any cmake files so I don't see how find package is supposed to be able to find it.

I was able to get cmake to succeed by setting `set(PlotJuggler_LIBRARY /usr/local/lib/libplotjuggler_plugin_base.a)`
But then the build fails with:
```
make[2]: *** No rule to make target '/usr/local/lib/libplotjuggler_plugin_base.a', needed by 'libDataLoadCAN.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:185: CMakeFiles/DataLoadCAN.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '/usr/local/lib/libplotjuggler_plugin_base.a', needed by 'libDataStreamCAN.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:214: CMakeFiles/DataStreamCAN.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
So clearly that's not the correct way to find the PlotJuggler library. Also another note, master does not build for me I had to checkout `bump-dbcppp-to-v3.2.1`

**Comment by kejava** [comment] 2022-01-23 21:59
Hi @Inquisitive-ME, 
I'm having a similar problem. What I'm finding is that my "libplotjuggler_plugin_base.a" is just not being built, or at least it's not located in /usr/local/lib or in the PJ build directory. I tried an extra time after satisfying all the dependencies except for mosquitto. Still, I'm not getting the libplotjuggler_plugin_base.a. All I can see in /usr/local/lib/ are these two files:
  libplotjuggler_base.a
  libplotjuggler_qwt.a
Could you double check that you really have libplotjuggler_plugin_base.a. Sorry to sound like I doubt you, not intended. I just want to ensure it's the same problem. It's also easy to overlook when there two files with "base" in them.

Hi @ozzdemir,
These seem like similar issues. If it turns out they're different, I'll start a separate thread. Can you think of any reason the that libplotjuggler_plugin_base.a isn't being built and/or installed to /usr/local/lib? Is there a way for me to force it during the build of PJ?

**Comment by Inquisitive-ME** [comment] 2022-01-23 22:11
@kejava I believe you are correct I just see `libplotjuggler_base.a ` I don't see how `libplotjuggler_plugin_base.a` would ever get built.

**Comment by kejava** [comment] 2022-01-24 01:21
I was thinking that it should get built during the default build of PlotJuggler. Maybe we need to force it somehow. I tried looking through the make files but I can't figure out how it gets made.

**Comment by ozzdemir** [comment] 2022-01-24 17:15
Thanks for your input, I tried to reproduce your error in a VM and was unable to fix it. (Problem wasn't persistent in my actual pc due to plotjuggler installation from catkin ). Inspecting your comments and https://github.com/PlotJuggler/plotjuggler-mqtt/issues/1#issuecomment-1008493947, fixed with latest commit. Let me hear if it also works for you or feel free to reopen the issue.

**Closed as completed** 2022-01-24 17:19 UTC

**Comment by ozzdemir** [comment] 2022-01-24 17:35
Seems like library name changed from _plotjuggler_plugin_base_ to _plotjuggler_base_  in https://github.com/facontidavide/PlotJuggler/commit/d35c5e015af9f7bdab96219d79e01a74f41d1689 , which was the root of the problem.

**Comment by kejava** [comment] 2022-01-25 03:05
Hi @ozzdemir,
Wow, that made a huge difference! I can build now without errors. One thing I had to do upgrade cmake in order for it to work. Mine was 3.13 on MX Linux. New setup requires 3.15 or greater so I bumped it to 3.16. For some reason PJ didn't need this.
I'm new to PJ and the use of the pluggins. What do I do after a successfule build, copy the entire "build" directory local the plotjuggler or just the *.so files?
Thanks again for all the help. I'm really looking forward to trying this out with my CAN bus.

**Comment by Inquisitive-ME** [comment] 2022-01-25 04:19
Worked for me but I also had to update the dbcppp submodule because it doesn't seem to build with the boost version it tries to download. But updating dbcppp to master seems to work.

**Comment by kejava** [comment] 2022-01-25 12:53
@Inquisitive-ME 
Yes, I wasn't using the "--recurse-submodules" in my git clone command initially. Seems to grab everything.
After you make the build, to use this plugin do you just copy the shared libs (.so) local to the PG app? Or do you need to copy the whole build folder?
My development is between different PCs, I plan to try this later.

**Comment by ozzdemir** [comment] 2022-01-25 13:11
@kejava, PJ has a way to add additional plugin directories to list of directories that will be searched. What I do is add build directory of this plugin to that list. Check https://github.com/facontidavide/PlotJuggler/issues/364#issuecomment-754590442

**Comment by kejava** [comment] 2022-01-26 00:52
@ozzdemir,
Thank you! This is working perfectly. I have a DAQ device broadcasting 4 channels of RTD data based on the byte stucture from a DBC file. PJ can now see it using SocketCAN. This is really cool!
